version: '3'
services:
  location-services:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: leoslassis/locations-services
    container_name: location-services
    ports:
      - '8080:8080'
    networks:
      - production-network
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "challenge"
    ports:
      - "3306:3306"
    volumes:
      - container-volume:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - production-network
volumes:
  container-volume:
networks:
  production-network:
    driver: bridge
